spring:
  datasource:
    url: jdbc:mysql://120.79.207.84:3306/hemiao?useSSL=true
    username: root
    password: 19980115
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

server:
  port: 8011
